### ISSUE TITLE
Is this milter used in production

### ISSUE THREAD

**Issue by amit777** [ktkmitani/node-milter#1]
Hello Kitani, i was browsing this project, and was wondering if you are currently using this milter in production.  It looks very interesting.

**Comment by ktkmitani** [comment]
Hello amit777, i'm using this milter in production.

**Comment by amit777** [comment]
Excellent. Could you provide any details on the number of emails per day or the type of email traffic being processed?

**Comment by ktkmitani** [comment]
I'm sorry. For the part of the system that are provided to my customer, I can't provide any details.
